version: '3.5'
services:
  api-backend:
    build: .
    volumes:
      - .:/ssfs-spotcode
    ports:
      - 3000:3000
    networks:
      - ssfs-spotcode
      - default
    depends_on:
      - api-db

  api-db:
    container_name: api-db
    image: postgres:11
    ports:
      - 4321:4321
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=api-db

networks:
  ssfs-spotcode:
